apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-bot-deployment
  labels:
    app: discord-bot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: discord-bot
  template:
    metadata:
      labels:
        app: discord-bot
    spec:
      containers:
      - name: discord-bot
        image: raniakh/discord_bot_quotes:latest
        ports:
        - containerPort: 40044
aapiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-bot-deployment
  labels:
    app: discord-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discord-bot
  template:
    metadata:
      labels:
        app: discord-bot
    spec:
      containers:
      - name: discord-bot
        env: 
          - name: DISCORD_TOKEN
            valueFrom:
              secretKeyRef:
                name: discord-secret
                key: token
        image: raniakh/discord_bot_quotes:latest
        ports:
        - containerPort: 40044
