name: ci-cd
on: [push]
jobs:
  CI:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: "Build base image"
        env:
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        run: |
            DOCKER_USER=raniakh
            docker login -u $DOCKER_USER -p $DOCKER_TOKEN
            docker build -t $DOCKER_USER/discord_bot_quotes_base:latest -f base.Dockerfile .
            docker push $DOCKER_USER/discord_bot_quotes_base:latest 
            docker logout 
      - name: "Build and containerize app"
        run: |
            DOCKER_USER=raniakh
            docker pull $DOCKER_USER/discord_bot_quotes_base:latest 
            docker tag $DOCKER_USER/discord_bot_quotes_base:latest discord_bot_quotes_base:latest 
            docker build -t discord_bot_quotes:latest -f Dockerfile src/
   
      - name: "Test containerized app"
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }} 
        run: |
          docker run -d --name bot -e DISCORD_TOKEN=${DISCORD_TOKEN} discord_bot_quotes:latest
          sleep 5
          docker ps --all
          curl localhost:40044
          docker logs bot
